use_frameworks!

target 'LDAutoCycleScrollView_Example' do
  pod 'LDAutoCycleScrollView', :path => '../'

  target 'LDAutoCycleScrollView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
